
export const firebaseAppConfig = JSON.parse(atob('eyJhcGlLZXkiOiJBSXphU3lDc016Vm9TSUZVWE5DbGdaeWlnNDgzQ0tVOThRbWJGSjQiLCJhdXRoRG9tYWluIjoiZ2VyLWdpbmFzdGljYS1lbGFib3JhbC5maXJlYmFzZWFwcC5jb20iLCJkYXRhYmFzZVVSTCI6Imh0dHBzOi8vZ2VyLWdpbmFzdGljYS1lbGFib3JhbC5maXJlYmFzZWlvLmNvbSIsInByb2plY3RJZCI6Imdlci1naW5hc3RpY2EtZWxhYm9yYWwiLCJzdG9yYWdlQnVja2V0IjoiZ2VyLWdpbmFzdGljYS1lbGFib3JhbC5hcHBzcG90LmNvbSIsIm1lc3NhZ2luZ1NlbmRlcklkIjoiMzA3ODEyNTMyMTkzIn0='));

export const saltSenhas = 'O rato roeu a roupa do rei de roma';
